package org.entitee;
// Generated 26 f�vr. 2025, 12:37:11 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Categorieinstitution generated by hbm2java
 */
@Entity
@Table(name = "categorieinstitution", schema = "public")
@SequenceGenerator(name = "global_seq", sequenceName = "global_seq", allocationSize = 1)

public class Categorieinstitution implements java.io.Serializable {

	private int idcatins;
	private String libelle;
	private Integer code;
	private String datecreation;
	private Integer nombreelements;
	private Set<Institution> institutions = new HashSet<Institution>(0);

	public Categorieinstitution() {
	}

	public Categorieinstitution(int idcatins) {
		this.idcatins = idcatins;
	}

	public Categorieinstitution(int idcatins, String libelle, Integer code, String datecreation, Integer nombreelements,
			Set<Institution> institutions) {
		this.idcatins = idcatins;
		this.libelle = libelle;
		this.code = code;
		this.datecreation = datecreation;
		this.nombreelements = nombreelements;
		this.institutions = institutions;
	}

	@Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "global_seq")
	@Column(name = "idcatins", unique = true, nullable = false)
	public int getIdcatins() {
		return this.idcatins;
	}

	public void setIdcatins(int idcatins) {
		this.idcatins = idcatins;
	}

	@Column(name = "libelle", length = 254)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Column(name = "code")
	public Integer getCode() {
		return this.code;
	}

	public void setCode(Integer code) {
		this.code = code;
	}

	@Column(name = "datecreation", length = 254)
	public String getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(String datecreation) {
		this.datecreation = datecreation;
	}

	@Column(name = "nombreelements")
	public Integer getNombreelements() {
		return this.nombreelements;
	}

	public void setNombreelements(Integer nombreelements) {
		this.nombreelements = nombreelements;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "categorieinstitution",cascade = CascadeType.ALL, orphanRemoval = true)
	public Set<Institution> getInstitutions() {
		return this.institutions;
	}

	public void setInstitutions(Set<Institution> institutions) {
		this.institutions = institutions;
	}

}
