package org.entitee;
// Generated 26 f�vr. 2025, 12:37:11 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Division generated by hbm2java
 */
@Entity
@Table(name = "division", schema = "public")
@SequenceGenerator(name = "global_seq", sequenceName = "global_seq", allocationSize = 1)

public class Division implements java.io.Serializable {

	private int iddivision;
	private Institution institution;
	private String libelle;
	private Integer code;
	private String datecreation;
	private String nombremembres;
	private String etat;
	private Set<Employe> employes = new HashSet<Employe>(0);

	public Division() {
	}

	public Division(int iddivision, Institution institution) {
		this.iddivision = iddivision;
		this.institution = institution;
	}

	public Division(int iddivision, Institution institution, String libelle, Integer code, String datecreation,
			String nombremembres, String etat, Set<Employe> employes) {
		this.iddivision = iddivision;
		this.institution = institution;
		this.libelle = libelle;
		this.code = code;
		this.datecreation = datecreation;
		this.nombremembres = nombremembres;
		this.etat = etat;
		this.employes = employes;
	}

	@Id    
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "global_seq")

	@Column(name = "iddivision", unique = true, nullable = false)
	public int getIddivision() {
		return this.iddivision;
	}

	public void setIddivision(int iddivision) {
		this.iddivision = iddivision;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idins", nullable = false)
	public Institution getInstitution() {
		return this.institution;
	}

	public void setInstitution(Institution institution) {
		this.institution = institution;
	}

	@Column(name = "libelle", length = 254)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Column(name = "code")
	public Integer getCode() {
		return this.code;
	}

	public void setCode(Integer code) {
		this.code = code;
	}

	@Column(name = "datecreation", length = 254)
	public String getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(String datecreation) {
		this.datecreation = datecreation;
	}

	@Column(name = "nombremembres", length = 254)
	public String getNombremembres() {
		return this.nombremembres;
	}

	public void setNombremembres(String nombremembres) {
		this.nombremembres = nombremembres;
	}

	@Column(name = "etat", length = 254)
	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "division",cascade = CascadeType.ALL, orphanRemoval = true)
	public Set<Employe> getEmployes() {
		return this.employes;
	}

	public void setEmployes(Set<Employe> employes) {
		this.employes = employes;
	}

}
