package org.entitee;
// Generated 26 f�vr. 2025, 12:37:11 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmployeId generated by hbm2java
 */
@Embeddable
public class EmployeId implements java.io.Serializable {

	private int idpersonne;
	private int idemploye;

	public EmployeId() {
	}

	public EmployeId(int idpersonne, int idemploye) {
		this.idpersonne = idpersonne;
		this.idemploye = idemploye;
	}

	@Column(name = "idpersonne", nullable = false)
	public int getIdpersonne() {
		return this.idpersonne;
	}

	public void setIdpersonne(int idpersonne) {
		this.idpersonne = idpersonne;
	}

	@Column(name = "idemploye", unique = true, nullable = false)
	public int getIdemploye() {
		return this.idemploye;
	}

	public void setIdemploye(int idemploye) {
		this.idemploye = idemploye;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmployeId))
			return false;
		EmployeId castOther = (EmployeId) other;

		return (this.getIdpersonne() == castOther.getIdpersonne()) && (this.getIdemploye() == castOther.getIdemploye());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdpersonne();
		result = 37 * result + this.getIdemploye();
		return result;
	}

}
