package org.entitee;
// Generated 26 f�vr. 2025, 12:37:11 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.config.HibernateUtil;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;

/**
 * Employe generated by hbm2java
 */
@Entity
@Table(name = "employe", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "idemploye"))
@SequenceGenerator(name = "global_seq", sequenceName = "global_seq", allocationSize = 1)

public class Employe implements java.io.Serializable {

	private EmployeId id;
	private Division division;
	private Institution institution;
	private Personne personne;
	private String matricule;
	private Integer codesecret;
	private String datecreation;
	private String etat;
	private Set<Reponse> reponses = new HashSet<Reponse>(0);

	public Employe() {
	}

	public Employe(EmployeId id, Institution institution, Personne personne) {
		this.id = id;
		this.institution = institution;
		this.personne = personne;
	}

	public Employe(EmployeId id, Division division, Institution institution, Personne personne, String matricule,
			Integer codesecret, String datecreation, String etat, Set<Reponse> reponses) {
		this.id = id;
		this.division = division;
		this.institution = institution;
		this.personne = personne;
		this.matricule = matricule;
		this.codesecret = codesecret;
		this.datecreation = datecreation;
		this.etat = etat;
		this.reponses = reponses;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idpersonne", column = @Column(name = "idpersonne", nullable = false)),
			@AttributeOverride(name = "idemploye", column = @Column(name = "idemploye", unique = true, nullable = false)) })
	public EmployeId getId() {
		return this.id;
	}
	

	public void setId(EmployeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "iddivision")
	public Division getDivision() {
		return this.division;
	}

	public void setDivision(Division division) {
		this.division = division;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idins", nullable = false)
	public Institution getInstitution() {
		return this.institution;
	}

	public void setInstitution(Institution institution) {
		this.institution = institution;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idpersonne", nullable = false, insertable = false, updatable = false)
	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	@Column(name = "matricule", length = 254)
	public String getMatricule() {
		return this.matricule;
	}

	public void setMatricule(String matricule) {
		this.matricule = matricule;
	}

	@Column(name = "codesecret")
	public Integer getCodesecret() {
		return this.codesecret;
	}

	public void setCodesecret(Integer codesecret) {
		this.codesecret = codesecret;
	}

	@Column(name = "datecreation", length = 254)
	public String getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(String datecreation) {
		this.datecreation = datecreation;
	}

	@Column(name = "etat", length = 254)
	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "employe",cascade = CascadeType.ALL, orphanRemoval = true)
	public Set<Reponse> getReponses() {
		return this.reponses;
	}

	public void setReponses(Set<Reponse> reponses) {
		this.reponses = reponses;
	}

}
