package org.entitee;
// Generated 26 f�vr. 2025, 12:37:11 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Itemquestion generated by hbm2java
 */
@Entity
@Table(name = "itemquestion", schema = "public")
@SequenceGenerator(name = "global_seq", sequenceName = "global_seq", allocationSize = 1)

public class Itemquestion implements java.io.Serializable {

	private int iditemquestion;
	private Question question;
	private String valeur;
	private String datecreation;
	private Integer numeroordre;

	public Itemquestion() {
	}

	public Itemquestion(int iditemquestion, Question question) {
		this.iditemquestion = iditemquestion;
		this.question = question;
	}

	public Itemquestion(int iditemquestion, Question question, String valeur, String datecreation,
			Integer numeroordre) {
		this.iditemquestion = iditemquestion;
		this.question = question;
		this.valeur = valeur;
		this.datecreation = datecreation;
		this.numeroordre = numeroordre;
	}

	@Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "global_seq")

	@Column(name = "iditemquestion", unique = true, nullable = false)
	public int getIditemquestion() {
		return this.iditemquestion;
	}

	public void setIditemquestion(int iditemquestion) {
		this.iditemquestion = iditemquestion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idquestion", nullable = false)
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@Column(name = "valeur")
	public String getValeur() {
		return this.valeur;
	}

	public void setValeur(String valeur) {
		this.valeur = valeur;
	}

	@Column(name = "datecreation", length = 254)
	public String getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(String datecreation) {
		this.datecreation = datecreation;
	}

	@Column(name = "numeroordre")
	public Integer getNumeroordre() {
		return this.numeroordre;
	}

	public void setNumeroordre(Integer numeroordre) {
		this.numeroordre = numeroordre;
	}

}
