package org.entitee;
// Generated 26 f�vr. 2025, 12:37:11 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name = "permission", schema = "public")
@SequenceGenerator(name = "global_seq", sequenceName = "global_seq", allocationSize = 1)

public class Permission implements java.io.Serializable {

	private int idpermission;
	private String permission;
	private Integer code;
	private String datecreation;
	private String etat;
	private Set<Rolepermission> rolepermissions = new HashSet<Rolepermission>(0);

	public Permission() {
	}

	public Permission(int idpermission) {
		this.idpermission = idpermission;
	}

	public Permission(int idpermission, String permission, Integer code, String datecreation, String etat,
			Set<Rolepermission> rolepermissions) {
		this.idpermission = idpermission;
		this.permission = permission;
		this.code = code;
		this.datecreation = datecreation;
		this.etat = etat;
		this.rolepermissions = rolepermissions;
	}

	@Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "global_seq")

	@Column(name = "idpermission", unique = true, nullable = false)
	public int getIdpermission() {
		return this.idpermission;
	}

	public void setIdpermission(int idpermission) {
		this.idpermission = idpermission;
	}

	@Column(name = "permission", length = 254)
	public String getPermission() {
		return this.permission;
	}

	public void setPermission(String permission) {
		this.permission = permission;
	}

	@Column(name = "code")
	public Integer getCode() {
		return this.code;
	}

	public void setCode(Integer code) {
		this.code = code;
	}

	@Column(name = "datecreation", length = 254)
	public String getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(String datecreation) {
		this.datecreation = datecreation;
	}

	@Column(name = "etat", length = 254)
	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permission",cascade = CascadeType.ALL, orphanRemoval = true)
	public Set<Rolepermission> getRolepermissions() {
		return this.rolepermissions;
	}

	public void setRolepermissions(Set<Rolepermission> rolepermissions) {
		this.rolepermissions = rolepermissions;
	}
	
	@Override
	public boolean equals(Object obj) {
	    if (this == obj)
	        return true;
	    if (obj == null || getClass() != obj.getClass())
	        return false;
	    Permission other = (Permission) obj;
	    return idpermission == other.idpermission;
	}

	@Override
	public int hashCode() {
	    return Integer.hashCode(idpermission);
	}


}
