package org.entitee;
// Generated 26 f�vr. 2025, 12:37:11 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Personne generated by hbm2java
 */
@Entity
@Table(name = "personne", schema = "public")
@SequenceGenerator(name = "global_seq", sequenceName = "global_seq", allocationSize = 1)

public class Personne implements java.io.Serializable {

	private int idpersonne;
	private Profile profile;
	private String nom;
	private String prenom;
	private String datenaiss;
	private String lieunaiss;
	private String cin;
	private String login;
	private String motpasse;
	private Integer telephone1;
	private Integer telephone2;
	private Integer telephone3;
	private String email1;
	private String email2;
	private String email3;
	private Integer codesecret;
	private String etat;
	private String bloque;
	private Set<Rolepermission> rolepermissions = new HashSet<Rolepermission>(0);
	private Set<Employe> employes = new HashSet<Employe>(0);

	public Personne() {
	}

	public Personne(int idpersonne, Profile profile) {
		this.idpersonne = idpersonne;
		this.profile = profile;
	}

	public Personne(int idpersonne, Profile profile, String nom, String prenom, String datenaiss, String lieunaiss,
			String cin, String login, String motpasse, Integer telephone1, Integer telephone2, Integer telephone3,
			String email1, String email2, String email3, Integer codesecret, String etat, String bloque,
			Set<Rolepermission> rolepermissions, Set<Employe> employes) {
		this.idpersonne = idpersonne;
		this.profile = profile;
		this.nom = nom;
		this.prenom = prenom;
		this.datenaiss = datenaiss;
		this.lieunaiss = lieunaiss;
		this.cin = cin;
		this.login = login;
		this.motpasse = motpasse;
		this.telephone1 = telephone1;
		this.telephone2 = telephone2;
		this.telephone3 = telephone3;
		this.email1 = email1;
		this.email2 = email2;
		this.email3 = email3;
		this.codesecret = codesecret;
		this.etat = etat;
		this.bloque = bloque;
		this.rolepermissions = rolepermissions;
		this.employes = employes;
	}

	@Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "global_seq")

	@Column(name = "idpersonne", unique = true, nullable = false)
	public int getIdpersonne() {
		return this.idpersonne;
	}

	public void setIdpersonne(int idpersonne) {
		this.idpersonne = idpersonne;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idprofile", nullable = false)
	public Profile getProfile() {
		return this.profile;
	}

	public void setProfile(Profile profile) {
		this.profile = profile;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 254)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "datenaiss", length = 254)
	public String getDatenaiss() {
		return this.datenaiss;
	}

	public void setDatenaiss(String datenaiss) {
		this.datenaiss = datenaiss;
	}

	@Column(name = "lieunaiss", length = 254)
	public String getLieunaiss() {
		return this.lieunaiss;
	}

	public void setLieunaiss(String lieunaiss) {
		this.lieunaiss = lieunaiss;
	}

	@Column(name = "cin", length = 254)
	public String getCin() {
		return this.cin;
	}

	public void setCin(String cin) {
		this.cin = cin;
	}

	@Column(name = "login", length = 254)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "motpasse", length = 254)
	public String getMotpasse() {
		return this.motpasse;
	}

	public void setMotpasse(String motpasse) {
		this.motpasse = motpasse;
	}

	@Column(name = "telephone1")
	public Integer getTelephone1() {
		return this.telephone1;
	}

	public void setTelephone1(Integer telephone1) {
		this.telephone1 = telephone1;
	}

	@Column(name = "telephone2")
	public Integer getTelephone2() {
		return this.telephone2;
	}

	public void setTelephone2(Integer telephone2) {
		this.telephone2 = telephone2;
	}

	@Column(name = "telephone3")
	public Integer getTelephone3() {
		return this.telephone3;
	}

	public void setTelephone3(Integer telephone3) {
		this.telephone3 = telephone3;
	}

	@Column(name = "email1", length = 254)
	public String getEmail1() {
		return this.email1;
	}

	public void setEmail1(String email1) {
		this.email1 = email1;
	}

	@Column(name = "email2", length = 254)
	public String getEmail2() {
		return this.email2;
	}

	public void setEmail2(String email2) {
		this.email2 = email2;
	}

	@Column(name = "email3", length = 254)
	public String getEmail3() {
		return this.email3;
	}

	public void setEmail3(String email3) {
		this.email3 = email3;
	}

	@Column(name = "codesecret")
	public Integer getCodesecret() {
		return this.codesecret;
	}

	public void setCodesecret(Integer codesecret) {
		this.codesecret = codesecret;
	}

	@Column(name = "etat", length = 254)
	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	@Column(name = "bloque", length = 254)
	public String getBloque() {
		return this.bloque;
	}

	public void setBloque(String bloque) {
		this.bloque = bloque;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "personne",cascade = CascadeType.ALL, orphanRemoval = true)
	public Set<Rolepermission> getRolepermissions() {
		return this.rolepermissions;
	}

	public void setRolepermissions(Set<Rolepermission> rolepermissions) {
		this.rolepermissions = rolepermissions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personne",cascade = CascadeType.ALL, orphanRemoval = true)
	public Set<Employe> getEmployes() {
		return this.employes;
	}

	public void setEmployes(Set<Employe> employes) {
		this.employes = employes;
	}

}
