package org.entitee;
// Generated 26 f�vr. 2025, 12:37:11 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Profile generated by hbm2java
 */
@Entity
@Table(name = "profile", schema = "public")
@SequenceGenerator(name = "global_seq", sequenceName = "global_seq", allocationSize = 1)

public class Profile implements java.io.Serializable {

	private int idprofile;
	private String libelle;
	private Integer code;
	private String datecreation;
	private Integer nombreindividus;
	private String etat;
	private Set<Personne> personnes = new HashSet<Personne>(0);

	public Profile() {
	}

	public Profile(int idprofile) {
		this.idprofile = idprofile;
	}

	public Profile(int idprofile, String libelle, Integer code, String datecreation, Integer nombreindividus,
			String etat, Set<Personne> personnes) {
		this.idprofile = idprofile;
		this.libelle = libelle;
		this.code = code;
		this.datecreation = datecreation;
		this.nombreindividus = nombreindividus;
		this.etat = etat;
		this.personnes = personnes;
	}

	@Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "global_seq")

	@Column(name = "idprofile", unique = true, nullable = false)
	public int getIdprofile() {
		return this.idprofile;
	}

	public void setIdprofile(int idprofile) {
		this.idprofile = idprofile;
	}

	@Column(name = "libelle", length = 254)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Column(name = "code")
	public Integer getCode() {
		return this.code;
	}

	public void setCode(Integer code) {
		this.code = code;
	}

	@Column(name = "datecreation", length = 254)
	public String getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(String datecreation) {
		this.datecreation = datecreation;
	}

	@Column(name = "nombreindividus")
	public Integer getNombreindividus() {
		return this.nombreindividus;
	}

	public void setNombreindividus(Integer nombreindividus) {
		this.nombreindividus = nombreindividus;
	}

	@Column(name = "etat", length = 254)
	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profile",cascade = CascadeType.ALL, orphanRemoval = true)
	public Set<Personne> getPersonnes() {
		return this.personnes;
	}

	public void setPersonnes(Set<Personne> personnes) {
		this.personnes = personnes;
	}

}
