package org.entitee;
// Generated 26 f�vr. 2025, 12:37:11 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Projet generated by hbm2java
 */
@Entity
@Table(name = "projet", schema = "public")
@SequenceGenerator(name = "global_seq", sequenceName = "global_seq", allocationSize = 1)

public class Projet implements java.io.Serializable {

	private int idprojet;
	private Institution institution;
	private String libelle;
	private Integer code;
	private String datecreation;
	private String datedebut;
	private String datefin;
    private String photo;
	private Integer budget;
	private Set<Questionnaire> questionnaires = new HashSet<Questionnaire>(0);

	public Projet() {
	}

	public Projet(int idprojet, Institution institution) {
		this.idprojet = idprojet;
		this.institution = institution;
	}

	public Projet(int idprojet, Institution institution, String libelle, Integer code, String datecreation,
			String datedebut, String datefin, Integer budget, Set<Questionnaire> questionnaires) {
		this.idprojet = idprojet;
		this.institution = institution;
		this.libelle = libelle;
		this.code = code;
		this.datecreation = datecreation;
		this.datedebut = datedebut;
		this.datefin = datefin;
		this.budget = budget;
		this.questionnaires = questionnaires;
	}

	@Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "global_seq")

	@Column(name = "idprojet", unique = true, nullable = false)
	public int getIdprojet() {
		return this.idprojet;
	}

	public void setIdprojet(int idprojet) {
		this.idprojet = idprojet;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idins", nullable = false)
	public Institution getInstitution() {
		return this.institution;
	}

	public void setInstitution(Institution institution) {
		this.institution = institution;
	}

	@Column(name = "libelle")
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Column(name = "code")
	public Integer getCode() {
		return this.code;
	}

	public void setCode(Integer code) {
		this.code = code;
	}

	@Column(name = "datecreation", length = 254)
	public String getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(String datecreation) {
		this.datecreation = datecreation;
	}

	@Column(name = "datedebut", length = 254)
	public String getDatedebut() {
		return this.datedebut;
	}

	public void setDatedebut(String datedebut) {
		this.datedebut = datedebut;
	}

	@Column(name = "datefin", length = 254)
	public String getDatefin() {
		return this.datefin;
	}

	public void setDatefin(String datefin) {
		this.datefin = datefin;
	}

	@Column(name = "budget")
	public Integer getBudget() {
		return this.budget;
	}

	public void setBudget(Integer budget) {
		this.budget = budget;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projet", cascade = CascadeType.ALL, orphanRemoval = true)
	public Set<Questionnaire> getQuestionnaires() {
		return this.questionnaires;
	}

	public void setQuestionnaires(Set<Questionnaire> questionnaires) {
		this.questionnaires = questionnaires;
	}

	public String getPhoto() {
		return photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

}
