package org.entitee;
// Generated 26 f�vr. 2025, 12:37:11 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "question", schema = "public")
@SequenceGenerator(name = "global_seq", sequenceName = "global_seq", allocationSize = 1)

public class Question implements java.io.Serializable {

	private int idquestion;
	private Questionnaire questionnaire;
	private String libelle;
	private Integer code;
	private String datecreation;
	private Integer numeroordre;
	private Integer nombrereponses;
	private String datepremieracces;
	private String datedernieraccces;
	private String optionel;
	private Integer autoriseremarque;
	private Set<Reponse> reponses = new HashSet<Reponse>(0);
	private Set<Itemquestion> itemquestions = new HashSet<Itemquestion>(0);

	public Question() {
	}

	public Question(int idquestion, Questionnaire questionnaire) {
		this.idquestion = idquestion;
		this.questionnaire = questionnaire;
	}

	public Question(int idquestion, Questionnaire questionnaire, String libelle, Integer code, String datecreation,
			Integer numeroordre, Integer nombrereponses, String datepremieracces, String datedernieraccces,
			String optionel, Integer autoriseremarque, Set<Reponse> reponses, Set<Itemquestion> itemquestions) {
		this.idquestion = idquestion;
		this.questionnaire = questionnaire;
		this.libelle = libelle;
		this.code = code;
		this.datecreation = datecreation;
		this.numeroordre = numeroordre;
		this.nombrereponses = nombrereponses;
		this.datepremieracces = datepremieracces;
		this.datedernieraccces = datedernieraccces;
		this.optionel = optionel;
		this.autoriseremarque = autoriseremarque;
		this.reponses = reponses;
		this.itemquestions = itemquestions;
	}

	@Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "global_seq")

	@Column(name = "idquestion", unique = true, nullable = false)
	public int getIdquestion() {
		return this.idquestion;
	}

	public void setIdquestion(int idquestion) {
		this.idquestion = idquestion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idquestionnaire", nullable = false)
	public Questionnaire getQuestionnaire() {
		return this.questionnaire;
	}

	public void setQuestionnaire(Questionnaire questionnaire) {
		this.questionnaire = questionnaire;
	}

	@Column(name = "libelle", length = 254)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Column(name = "code")
	public Integer getCode() {
		return this.code;
	}

	public void setCode(Integer code) {
		this.code = code;
	}

	@Column(name = "datecreation", length = 254)
	public String getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(String datecreation) {
		this.datecreation = datecreation;
	}

	@Column(name = "numeroordre")
	public Integer getNumeroordre() {
		return this.numeroordre;
	}

	public void setNumeroordre(Integer numeroordre) {
		this.numeroordre = numeroordre;
	}

	@Column(name = "nombrereponses")
	public Integer getNombrereponses() {
		return this.nombrereponses;
	}

	public void setNombrereponses(Integer nombrereponses) {
		this.nombrereponses = nombrereponses;
	}

	@Column(name = "datepremieracces", length = 254)
	public String getDatepremieracces() {
		return this.datepremieracces;
	}

	public void setDatepremieracces(String datepremieracces) {
		this.datepremieracces = datepremieracces;
	}

	@Column(name = "datedernieraccces", length = 254)
	public String getDatedernieraccces() {
		return this.datedernieraccces;
	}

	public void setDatedernieraccces(String datedernieraccces) {
		this.datedernieraccces = datedernieraccces;
	}

	@Column(name = "optionel", length = 254)
	public String getOptionel() {
		return this.optionel;
	}

	public void setOptionel(String optionel) {
		this.optionel = optionel;
	}

	@Column(name = "autoriseremarque")
	public Integer getAutoriseremarque() {
		return this.autoriseremarque;
	}

	public void setAutoriseremarque(Integer autoriseremarque) {
		this.autoriseremarque = autoriseremarque;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "question",cascade = CascadeType.ALL, orphanRemoval = true)
	public Set<Reponse> getReponses() {
		return this.reponses;
	}

	public void setReponses(Set<Reponse> reponses) {
		this.reponses = reponses;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "question",cascade = CascadeType.ALL, orphanRemoval = true)
	public Set<Itemquestion> getItemquestions() {
		return this.itemquestions;
	}

	public void setItemquestions(Set<Itemquestion> itemquestions) {
		this.itemquestions = itemquestions;
	}

}
