package org.entitee;
// Generated 26 f�vr. 2025, 12:37:11 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Questionnaire generated by hbm2java
 */
@Entity
@Table(name = "questionnaire", schema = "public")
@SequenceGenerator(name = "global_seq", sequenceName = "global_seq", allocationSize = 1)

public class Questionnaire implements java.io.Serializable {

	private int idquestionnaire;
	private Projet projet;
	private String libelle;
	private String objectif;
	private Integer code;
	private String datecreation;
	private Integer nombrequestions;
	private Integer nombreacces;
	private Integer nombretraitements;
	private String etat;
	private String datedebut;
	private String datefin;
	private String remarque;
	private String infos;
	private Set<Question> questions = new HashSet<Question>(0);

	public Questionnaire() {
	}

	public Questionnaire(int idquestionnaire, Projet projet) {
		this.idquestionnaire = idquestionnaire;
		this.projet = projet;
	}

	public Questionnaire(int idquestionnaire, Projet projet, String libelle, String objectif, Integer code,
			String datecreation, Integer nombrequestions, Integer nombreacces, Integer nombretraitements, String etat,
			String datedebut, String datefin, String remarque, String infos, Set<Question> questions) {
		this.idquestionnaire = idquestionnaire;
		this.projet = projet;
		this.libelle = libelle;
		this.objectif = objectif;
		this.code = code;
		this.datecreation = datecreation;
		this.nombrequestions = nombrequestions;
		this.nombreacces = nombreacces;
		this.nombretraitements = nombretraitements;
		this.etat = etat;
		this.datedebut = datedebut;
		this.datefin = datefin;
		this.remarque = remarque;
		this.infos = infos;
		this.questions = questions;
	}

	@Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "global_seq")

	@Column(name = "idquestionnaire", unique = true, nullable = false)
	public int getIdquestionnaire() {
		return this.idquestionnaire;
	}

	public void setIdquestionnaire(int idquestionnaire) {
		this.idquestionnaire = idquestionnaire;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idprojet", nullable = false)
	public Projet getProjet() {
		return this.projet;
	}

	public void setProjet(Projet projet) {
		this.projet = projet;
	}

	@Column(name = "libelle", length = 254)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Column(name = "objectif")
	public String getObjectif() {
		return this.objectif;
	}

	public void setObjectif(String objectif) {
		this.objectif = objectif;
	}

	@Column(name = "code")
	public Integer getCode() {
		return this.code;
	}

	public void setCode(Integer code) {
		this.code = code;
	}

	@Column(name = "datecreation", length = 254)
	public String getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(String datecreation) {
		this.datecreation = datecreation;
	}

	@Column(name = "nombrequestions")
	public Integer getNombrequestions() {
		return this.nombrequestions;
	}

	public void setNombrequestions(Integer nombrequestions) {
		this.nombrequestions = nombrequestions;
	}

	@Column(name = "nombreacces")
	public Integer getNombreacces() {
		return this.nombreacces;
	}

	public void setNombreacces(Integer nombreacces) {
		this.nombreacces = nombreacces;
	}

	@Column(name = "nombretraitements")
	public Integer getNombretraitements() {
		return this.nombretraitements;
	}

	public void setNombretraitements(Integer nombretraitements) {
		this.nombretraitements = nombretraitements;
	}

	@Column(name = "etat", length = 254)
	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	@Column(name = "datedebut", length = 254)
	public String getDatedebut() {
		return this.datedebut;
	}

	public void setDatedebut(String datedebut) {
		this.datedebut = datedebut;
	}

	@Column(name = "datefin", length = 254)
	public String getDatefin() {
		return this.datefin;
	}

	public void setDatefin(String datefin) {
		this.datefin = datefin;
	}

	@Column(name = "remarque")
	public String getRemarque() {
		return this.remarque;
	}

	public void setRemarque(String remarque) {
		this.remarque = remarque;
	}

	@Column(name = "infos")
	public String getInfos() {
		return this.infos;
	}

	public void setInfos(String infos) {
		this.infos = infos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "questionnaire",cascade = CascadeType.ALL, orphanRemoval = true)
	public Set<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set<Question> questions) {
		this.questions = questions;
	}

}
