package org.entitee;
// Generated 26 f�vr. 2025, 12:37:11 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Reponse generated by hbm2java
 */
@Entity
@Table(name = "reponse", schema = "public")
@SequenceGenerator(name = "global_seq", sequenceName = "global_seq", allocationSize = 1)

public class Reponse implements java.io.Serializable {

	private int idreponse;
	private Employe employe;
	private Question question;
	private String valeur;
	private String datereponse;
	private String etat;
	private Integer nombreaccesquestion;
	private String remarque;

	public Reponse() {
	}

	public Reponse(int idreponse, Employe employe, Question question) {
		this.idreponse = idreponse;
		this.employe = employe;
		this.question = question;
	}

	public Reponse(int idreponse, Employe employe, Question question, String valeur, String datereponse, String etat,
			Integer nombreaccesquestion, String remarque) {
		this.idreponse = idreponse;
		this.employe = employe;
		this.question = question;
		this.valeur = valeur;
		this.datereponse = datereponse;
		this.etat = etat;
		this.nombreaccesquestion = nombreaccesquestion;
		this.remarque = remarque;
	}

	@Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "global_seq")

	@Column(name = "idreponse", unique = true, nullable = false)
	public int getIdreponse() {
		return this.idreponse;
	}

	public void setIdreponse(int idreponse) {
		this.idreponse = idreponse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "idpersonne", referencedColumnName = "idpersonne", nullable = false),
			@JoinColumn(name = "idemploye", referencedColumnName = "idemploye", nullable = false) })
	public Employe getEmploye() {
		return this.employe;
	}

	public void setEmploye(Employe employe) {
		this.employe = employe;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idquestion", nullable = false)
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@Column(name = "valeur")
	public String getValeur() {
		return this.valeur;
	}

	public void setValeur(String valeur) {
		this.valeur = valeur;
	}

	@Column(name = "datereponse", length = 254)
	public String getDatereponse() {
		return this.datereponse;
	}

	public void setDatereponse(String datereponse) {
		this.datereponse = datereponse;
	}

	@Column(name = "etat", length = 254)
	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	@Column(name = "nombreaccesquestion")
	public Integer getNombreaccesquestion() {
		return this.nombreaccesquestion;
	}

	public void setNombreaccesquestion(Integer nombreaccesquestion) {
		this.nombreaccesquestion = nombreaccesquestion;
	}

	@Column(name = "remarque")
	public String getRemarque() {
		return this.remarque;
	}

	public void setRemarque(String remarque) {
		this.remarque = remarque;
	}

}
