package org.entitee;
// Generated 26 f�vr. 2025, 12:37:11 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RolepermissionId generated by hbm2java
 */
@Embeddable
public class RolepermissionId implements java.io.Serializable {

	private int idpersonne;
	private int idpermission;

	public RolepermissionId() {
	}

	public RolepermissionId(int idpersonne, int idpermission) {
		this.idpersonne = idpersonne;
		this.idpermission = idpermission;
	}

	@Column(name = "idpersonne", nullable = false)
	public int getIdpersonne() {
		return this.idpersonne;
	}

	public void setIdpersonne(int idpersonne) {
		this.idpersonne = idpersonne;
	}

	@Column(name = "idpermission", nullable = false)
	public int getIdpermission() {
		return this.idpermission;
	}

	public void setIdpermission(int idpermission) {
		this.idpermission = idpermission;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RolepermissionId))
			return false;
		RolepermissionId castOther = (RolepermissionId) other;

		return (this.getIdpersonne() == castOther.getIdpersonne())
				&& (this.getIdpermission() == castOther.getIdpermission());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdpersonne();
		result = 37 * result + this.getIdpermission();
		return result;
	}

}
