package org.entitee;
// Generated 26 f�vr. 2025, 12:37:11 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Rolepermission generated by hbm2java
 */
@Entity
@Table(name = "rolepermission", schema = "public")
@SequenceGenerator(name = "global_seq", sequenceName = "global_seq", allocationSize = 1)

public class Rolepermission implements java.io.Serializable {

	private RolepermissionId id;
	private Permission permission;
	private Personne personne;
	private String datecreation;
	private String etat;

	public Rolepermission() {
	}

	public Rolepermission(RolepermissionId id, Permission permission, Personne personne) {
		this.id = id;
		this.permission = permission;
		this.personne = personne;
	}

	public Rolepermission(RolepermissionId id, Permission permission, Personne personne, String datecreation,
			String etat) {
		this.id = id;
		this.permission = permission;
		this.personne = personne;
		this.datecreation = datecreation;
		this.etat = etat;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idpersonne", column = @Column(name = "idpersonne", nullable = false)),
			@AttributeOverride(name = "idpermission", column = @Column(name = "idpermission", nullable = false)) })
	public RolepermissionId getId() {
		return this.id;
	}

	public void setId(RolepermissionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idpermission", nullable = false, insertable = false, updatable = false)
	public Permission getPermission() {
		return this.permission;
	}

	public void setPermission(Permission permission) {
		this.permission = permission;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpersonne", nullable = false, insertable = false, updatable = false)
	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	@Column(name = "datecreation", length = 254)
	public String getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(String datecreation) {
		this.datecreation = datecreation;
	}

	@Column(name = "etat", length = 254)
	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

}
